# 編譯外術
pre-build:
	just 外術/build

build target:
	cargo run {{target}} # 加入 -O2 啟用優化
	riscv64-unknown-elf-gcc -g {{target}}.S 外術/曰.o

run target: (build target)
	qemu-riscv64 a.out
	echo $?

debug target: (build target)
	qemu-riscv64 -g 1234 a.out # 在 1234 埠口啟動 gdb 伺服器
	echo $?

