emulator-run := if os() == "linux" { "qemu-riscv64" } else { "rvlinux" }
emulator-debug := if os() == "linux" { "qemu-riscv64 -g 2159" } else { "rvlinux --gdb" }

# 編譯外術
pre-build:
	just 外術/build

build target:
	cargo run {{target}} # 加入 -O2 啟用優化
	riscv64-linux-gnu-gcc -static -g {{target}}.S 外術/曰.o

run target: (build target)
	{{emulator-run}} a.out

debug target: (build target)
	{{emulator-debug}} a.out # 在 2159 埠口啟動 gdb 伺服器

test:
    ./腳本/整合測試.sh

